### ISSUE TITLE
Could not pass event PlayerMoveEvent to WeatherMan v1.1.0

### ISSUE THREAD

**Issue by JhOnNeY** [fromgate/WeatherMan#4]
Using "Last stable build (#7), 12 hr ago)" from the athion build

**This happens when anyone moves:**
_[19:13:13 ERROR]: Could not pass event PlayerMoveEvent to WeatherMan v1.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-7d78b81-f709362]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-7d78b81-f709362]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:615) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_112]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot_server.jar:git-Spigot-7d78b81-f709362]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NullPointerException_

**Occasionally the line:**
_at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot_server.jar:git-Spigot-7d78b81-f709362]_

**will instead say**
_at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:18) [spigot_server.jar:git-Spigot-7d78b81-f709362]_

**Comment by JhOnNeY** [comment]
If you don't want me posting this stuff here please let me know. 

I'm just here as a cheerleader, EXCITEMENT!!!
I'm HYPED 👍
