### ISSUE TITLE
please update to 1.12.2

### ISSUE THREAD

**Issue by seema84** [fromgate/WeatherMan#6]
issued server command: /wm give biome
[00:17:27 INFO]: [WeatherMan] his version of WeatherMan is not compatible with CraftBukkit git-Spigot-7754231-94b0980 (MC: 1.12.2)
[00:17:27 INFO]: [WeatherMan] Features depended to craftbukkit version will be disabled!
[00:17:27 INFO]: [WeatherMan] + It is strongly recommended to update WeatherMan to latest version!
[00:17:27 INFO]: [WeatherMan] + Check updates at http://dev.bukkit.org/server-mods/wm/
[00:17:27 INFO]: [WeatherMan] + or use this version at your own risk.
[00:17:27 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.ChunkProviderServer.saveChunk(net.minecraft.server.v1_12_R1.Chunk)
[00:17:27 WARN]: 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
[00:17:27 WARN]: 	at me.fromgate.weatherman.util.NMSUtil.<clinit>(NMSUtil.java:127)
[00:17:27 WARN]: 	at me.fromgate.weatherman.queue.WMChunk.processChunk(WMChunk.java:91)
[00:17:27 WARN]: 	at me.fromgate.weatherman.queue.Queue.processQueue(Queue.java:108)
[00:17:27 WARN]: 	at me.fromgate.weatherman.queue.QueueManager$1.run(QueueManager.java:133)
[00:17:27 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[00:17:27 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[00:17:27 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[00:17:27 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[00:17:27 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[00:17:27 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[00:17:27 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by fromgate** [comment]
Thanks for informing. I will check it today.

**Comment by fromgate** [comment]
Fixed
https://circleci.com/gh/fromgate/WeatherMan/25

**Comment by seema84** [comment]
thanks fromgate, build 25 works fine
maybe you can upload this on bukkit for other people ;-)

**Comment by seema84** [comment]
oh wait i have a problem ... i stuck in the air if i use the wand tool

**Comment by fromgate** [comment]
Already uploaded. Waiting for approval.

I noticed same kind of lags too. And they are related to related to chunk update function.
And I still can't find a optimal way to update biomes visually :(
I hope sometime I will fix this issue too.

**Comment by seema84** [comment]
I'm sure you will find a good way to fix this. :-)
